Repository NewTec-GmbH/pyPolarionCli, pull requests merged in 2024-06, with the labels that each got.

#1 Created project structure
  .github/workflows/ci.yml
  .gitignore
  .vscode/settings.json
  design/README.md
  examples/README.md
  pyproject.toml
  src/pyPolarionCli/__init__.py
  src/pyPolarionCli/__main__.py
  src/pyPolarionCli/version.py
  tests/__init__.py
  tests/test_empty.py
Labels: enhancement

#5 Added template for Python file
  .vscode/templates.code-snippets
Labels: enhancement

#6 #4 main entry point
  src/pyPolarionCli/__main__.py
  src/pyPolarionCli/ret.py
Labels: enhancement

#8 Added missing setup files
  setup.cfg
  setup.py
Labels: bug

#9 Search command
  .gitignore
  src/pyPolarionCli/__main__.py
  src/pyPolarionCli/cmd_search.py
  src/pyPolarionCli/ret.py
Labels: enhancement

#13 Loggers
  src/pyPolarionCli/__main__.py
  src/pyPolarionCli/cmd_search.py
Labels: enhancement

#12 PyInstaller
  src/pyPolarionCli/__main__.py
  src/pyPolarionCli/cmd_search.py
  tools/create_executable.bat
Labels: enhancement

#14 Argument groups
  src/pyPolarionCli/__main__.py
  src/pyPolarionCli/cmd_search.py
Labels: enhancement

#15 Documentation
  README.md
  design/UML/cmd_search_sequence.puml
  design/UML/context.puml
  examples/README.md
  examples/search/search.bat
  src/pyPolarionCli/cmd_search.py
Labels: documentation

#17 Full item search
  src/pyPolarionCli/cmd_search.py
Labels: enhancement
